ktor:
  application:
    modules:
      - com.helcode.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  secret: "Helcode" # Agrega el secret aquí
  issuer: "https://jwt-provider-domain/" # Correcto: Cambiado de 'domain' a 'issuer'
  audience: "jwt-audience"
  realm: "ktor sample app"